export const translations = {
  en: {
    appTitle: 'SchemeReady', appSubtitle: 'From Scheme Discovery to Application Readiness', tagline: 'Connecting entrepreneurs and students to verified government schemes and channel partners.', demoPersonaBtn: 'Load Demo Persona (Ravi - Bengaluru)', loginBtn: 'Login / Register', profileTab: 'Beneficiary Profile',
    tabs: { onboarding: '1. Smart Onboarding', profile: 'Profile Dossier', schemes: '2. Scheme Matcher', readiness: '3. Readiness Score', businessPlan: '4. AI Project Report', checklist: '5. Document Checklist', partners: '6. Partner Routing', emi: '7. EMI Simulator', applicationPack: '8. Application Pack', admin: 'Admin Portal' },
    onboarding: { title: 'Smart Beneficiary Onboarding', subtitle: 'Answer a few simple questions or use voice input to discover matching schemes.', voiceBtn: 'Voice Input (Speak)', listening: 'Listening... Speak in English or your regional language', extractedBadge: 'Extracted Beneficiary Profile', q1: 'What do you want to start or pursue?', q2: 'Where is your project/business located?', q3: 'What is the estimated project cost?', q4: 'What is your annual family income?', q5: 'Are you a student, existing entrepreneur, or first-time entrepreneur?', q6: 'Do you have a caste certificate?', q7: 'Do you have an income certificate or ITR?', q8: 'How much loan do you need?', q9: 'Do you prefer online or offline support?', q10: 'Which language do you prefer?', nextBtn: 'Next Question', prevBtn: 'Back', submitBtn: 'Find Matching Schemes' },
    schemes: { title: 'Explainable Scheme Recommendations', subtitle: "Transparent ranking with clear 'Why it matches' and 'Why not' explanations.", matchScore: 'Match Score', whyMatches: 'Criteria Met & Why It Matches:', whyNot: 'Why Not Selected / Score Deductions:', recommended: 'Recommended Scheme', interestRate: 'Interest Rate', maxLoan: 'Max Loan Limit', tenure: 'Max Tenure', source: 'Official Source', verified: 'Last Verified', selectBtn: 'Select & View Readiness' },
    readiness: { title: 'Application Readiness Score', subtitle: 'Track missing requirements before visiting the bank or SCA office.', scoreLabel: 'Application Readiness', whyReq: 'Why required:', howTo: 'How to obtain:', accepted: 'Accepted formats:', uploadBtn: 'Upload Document', statusVerified: 'Verified', statusComplete: 'Complete', statusMissing: 'Missing', statusPending: 'Pending Review' },
    businessPlan: { title: 'AI Business-Plan & Project Report Builder', subtitle: 'Generate a submission-ready one-page project viability report.', generateBtn: 'Generate Project Report', dscr: 'Debt Service Coverage Ratio (DSCR)', monthlySurplus: 'Net Monthly Surplus', bankLoan: 'Recommended Loan Amount' },
    partners: { title: 'Smart Channel Partner Routing', subtitle: 'Locate verified channel partners for application submission.', recommendedBadge: 'Recommended Nearest Partner', distance: 'Distance', mode: 'Submission Mode', verifiedDate: 'Last Verified', contact: 'Contact Officer' },
    emi: { title: 'EMI & Financial Calculator', subtitle: 'Calculate monthly installments, interest, and moratorium relief.', monthlyEmi: 'Monthly EMI', totalInterest: 'Total Interest', totalRepayment: 'Total Repayment', moratoriumBuffer: 'Moratorium Buffer' },
    pack: { title: 'Submission-Ready Application Pack', subtitle: 'Download, print, or hand off your complete dossier.', downloadPdf: 'Download / Print Dossier', shareWhatsApp: 'Share via WhatsApp', handoffBtn: 'Proceed to PM-SURAJ Handoff', disclaimer: 'This is a preliminary assistance document. Final approval is determined by the authorised government agency or bank.' },
    navbar: { topBannerTitle: 'National Concessional Entrepreneurship & Credit Platform', cleanBalanceSheet: '● Clean Balance Sheet & 0% Overdue Verified', citizenPortal: 'Citizen Portal', raviPersonaMobile: 'Ravi Persona', homePortal: '🏠 Home / Portal', signOut: 'Sign out', signIn: 'Sign in', sihEdition: 'SIH Edition', raviPersona: 'Ravi Persona', demoPersonaTitle: "Auto-fill Ravi's demo persona", languageLabel: 'Select language', primaryNavigation: 'Primary navigation' },
    govHeader: { systemBanner: 'Government of India & NSFDC Channel Finance System | PM-SURAJ Aligned' },
    common: { loading: 'Loading…', save: 'Save', cancel: 'Cancel', close: 'Close', next: 'Next', back: 'Back', search: 'Search', submit: 'Submit', yes: 'Yes', no: 'No', notAvailable: 'Not available', preliminary: 'Preliminary guidance' },
    auth: { udyamSaarthi: 'UDYAM SAARTHI', readinessPortal: 'National Concessional Credit Readiness Portal', sovereignGateway: 'Sovereign Citizen Gateway', ministrySubtitle: 'Under NSFDC & Ministry of Social Justice and Empowerment', aiMatching: 'AI-Powered Scheme Matching', aiMatchingDesc: 'Explainable matching to relevant government schemes.', collateralFree: 'Readiness Check', collateralFreeDesc: 'Track application readiness before submission.', digilocker: 'DigiLocker Verification', digilockerDesc: 'Verify government documents.', channelRouting: 'Channel Partner Routing', channelRoutingDesc: 'Find authorised application channels.', encryption: '256-Bit AES Encryption', compliance: 'DPDP Act 2023 Compliant', dbtReady: 'Direct Benefit Transfer (DBT) Ready Infrastructure', signInTab: 'Sign In to Account', signUpTab: 'Register (Sign Up)', loginHeading: 'Access Your Beneficiary Dossier', signupHeading: 'Create Your Citizen Account', loginDesc: 'Sign in to access your saved profile and application readiness.', signupDesc: 'Register to check scheme eligibility and track your application.', fullNameLabel: 'Full Name (as on Aadhaar)', emailLabel: 'Email Address', passwordLabel: 'Password', forgotPassword: 'Forgot password?', passwordPlaceholder: 'Create a secure password (8+ chars)', passwordLoginPlaceholder: 'Enter your password', rememberMe: 'Keep me signed in', signInBtn: 'Sign In to SchemeReady', signUpBtn: 'Create Citizen Account', processing: 'Processing securely…', evaluatorFast: 'Evaluator Fast-Access', oneClick: '1-Click Sign In', evalRavi: 'Ravi Kumar (Beneficiary)', evalOfficer: 'SCA Officer (Admin)', noAccountYet: "Don't have a SchemeReady account yet?", registerNew: 'Register new account →', alreadyAccount: 'Already have a registered account?', signInHere: 'Sign in here →' },
    assistant: { title: 'Ask SchemeReady', close: 'Close assistant', listening: 'Listening…', speak: 'Speak', stopListening: 'Stop listening', send: 'Send message', stopSpeaking: 'Stop speaking', startSpeaking: 'Read aloud', online: 'Voice ready', textFallback: 'Voice is unavailable in this browser. Type your question below.', schemeDetails: 'Scheme details', eligibility: 'Eligibility', benefits: 'Benefits', documents: 'Documents', application: 'How to apply', nextStep: 'Next step' }
  },
  hi: {
    appTitle: 'स्कीमरेडी', appSubtitle: 'योजना खोज से आवेदन तैयारी तक', tagline: 'उद्यमियों और छात्रों को सत्यापित सरकारी योजनाओं और चैनल पार्टनर्स से जोड़ना।', demoPersonaBtn: 'डेमो प्रोफ़ाइल लोड करें (रवि - बेंगलुरु)', loginBtn: 'लॉगिन / रजिस्टर', profileTab: 'लाभार्थी प्रोफ़ाइल',
    tabs: { onboarding: '1. स्मार्ट ऑनबोर्डिंग', profile: 'प्रोफ़ाइल डोज़ियर', schemes: '2. योजना मिलान', readiness: '3. आवेदन तैयारी स्कोर', businessPlan: '4. AI प्रोजेक्ट रिपोर्ट', checklist: '5. दस्तावेज़ चेकलिस्ट', partners: '6. पार्टनर रूटिंग', emi: '7. EMI सिम्युलेटर', applicationPack: '8. आवेदन पैक', admin: 'एडमिन पोर्टल' },
    onboarding: { title: 'स्मार्ट लाभार्थी ऑनबोर्डिंग', subtitle: 'कुछ सरल प्रश्नों के उत्तर दें या आवाज़ से बोलकर उपयुक्त योजनाएँ खोजें।', voiceBtn: 'वॉइस इनपुट (बोलें)', listening: 'सुन रहा है… हिंदी में बोलें', extractedBadge: 'पहचानी गई लाभार्थी प्रोफ़ाइल', q1: 'आप कौन सा व्यवसाय या कार्य शुरू करना चाहते हैं?', q2: 'आपका व्यवसाय कहाँ स्थित है?', q3: 'अनुमानित परियोजना लागत कितनी है?', q4: 'आपकी वार्षिक पारिवारिक आय कितनी है?', q5: 'क्या आप छात्र, मौजूदा उद्यमी या पहली बार उद्यमी हैं?', q6: 'क्या आपके पास जाति प्रमाणपत्र है?', q7: 'क्या आपके पास आय प्रमाणपत्र या ITR है?', q8: 'आपको कितने ऋण की आवश्यकता है?', q9: 'आप ऑनलाइन या ऑफलाइन सहायता चाहते हैं?', q10: 'आप कौन सी भाषा पसंद करते हैं?', nextBtn: 'अगला प्रश्न', prevBtn: 'वापस', submitBtn: 'मिलान वाली योजनाएँ खोजें' },
    schemes: { title: 'समझाने योग्य योजना सिफारिशें', subtitle: 'योजना क्यों मेल खाती है और क्यों नहीं, इसकी स्पष्ट जानकारी।', matchScore: 'मिलान स्कोर', whyMatches: 'पूरे मानदंड और मिलान का कारण:', whyNot: 'क्यों नहीं चुना गया / स्कोर कटौती:', recommended: 'अनुशंसित योजना', interestRate: 'ब्याज दर', maxLoan: 'अधिकतम ऋण सीमा', tenure: 'अधिकतम अवधि', source: 'आधिकारिक स्रोत', verified: 'अंतिम सत्यापन', selectBtn: 'चुनें और तैयारी देखें' },
    readiness: { title: 'आवेदन तैयारी स्कोर', subtitle: 'बैंक या SCA कार्यालय जाने से पहले लंबित आवश्यकताओं को देखें।', scoreLabel: 'आवेदन तैयारी', whyReq: 'क्यों आवश्यक:', howTo: 'कैसे प्राप्त करें:', accepted: 'स्वीकृत प्रारूप:', uploadBtn: 'दस्तावेज़ अपलोड करें', statusVerified: 'सत्यापित', statusComplete: 'पूर्ण', statusMissing: 'अनुपलब्ध', statusPending: 'समीक्षा लंबित' },
    businessPlan: { title: 'AI बिज़नेस प्लान और प्रोजेक्ट रिपोर्ट', subtitle: 'जमा करने योग्य प्रोजेक्ट व्यवहार्यता रिपोर्ट बनाएँ।', generateBtn: 'प्रोजेक्ट रिपोर्ट बनाएँ', dscr: 'ऋण सेवा कवरेज अनुपात (DSCR)', monthlySurplus: 'मासिक शुद्ध अधिशेष', bankLoan: 'अनुशंसित ऋण राशि' },
    partners: { title: 'स्मार्ट चैनल पार्टनर रूटिंग', subtitle: 'आवेदन जमा करने के लिए सत्यापित चैनल पार्टनर खोजें।', recommendedBadge: 'निकटतम अनुशंसित पार्टनर', distance: 'दूरी', mode: 'आवेदन माध्यम', verifiedDate: 'अंतिम सत्यापन', contact: 'संपर्क अधिकारी' },
    emi: { title: 'EMI और वित्तीय कैलकुलेटर', subtitle: 'मासिक किस्त, ब्याज और मोरेटोरियम की गणना करें।', monthlyEmi: 'मासिक EMI', totalInterest: 'कुल ब्याज', totalRepayment: 'कुल भुगतान', moratoriumBuffer: 'मोरेटोरियम बफर' },
    pack: { title: 'आवेदन-तैयार पैक', subtitle: 'पूरा डोज़ियर डाउनलोड, प्रिंट या हस्तांतरित करें।', downloadPdf: 'PDF डाउनलोड / प्रिंट', shareWhatsApp: 'WhatsApp से साझा करें', handoffBtn: 'PM-SURAJ हैंडऑफ पर जाएँ', disclaimer: 'यह प्रारंभिक सहायता दस्तावेज़ है। अंतिम स्वीकृति अधिकृत सरकारी एजेंसी या बैंक द्वारा निर्धारित की जाती है।' },
    navbar: { cleanBalanceSheet: '● क्लीन बैलेंस शीट और 0% ओवरड्यू सत्यापित', sihEdition: 'SIH संस्करण', raviPersona: 'रवि प्रोफ़ाइल', demoPersonaTitle: 'रवि की डेमो प्रोफ़ाइल भरें', languageLabel: 'भाषा चुनें', primaryNavigation: 'मुख्य नेविगेशन', signOut: 'साइन आउट', signIn: 'साइन इन' }, govHeader: { systemBanner: 'भारत सरकार और NSFDC चैनल वित्त प्रणाली | PM-SURAJ अनुरूप' }, common: { loading: 'लोड हो रहा है…', save: 'सहेजें', cancel: 'रद्द करें', close: 'बंद करें', next: 'अगला', back: 'वापस', search: 'खोजें', submit: 'जमा करें', yes: 'हाँ', no: 'नहीं', notAvailable: 'उपलब्ध नहीं', preliminary: 'प्रारंभिक मार्गदर्शन' }, auth: { signInTab: 'खाते में साइन इन', signUpTab: 'रजिस्टर', loginHeading: 'अपना लाभार्थी डोज़ियर खोलें', signupHeading: 'अपना नागरिक खाता बनाएँ', loginDesc: 'अपनी प्रोफ़ाइल और आवेदन तैयारी तक पहुँचने के लिए साइन इन करें।', signupDesc: 'योजना पात्रता जाँचने और आवेदन ट्रैक करने के लिए रजिस्टर करें।', fullNameLabel: 'पूरा नाम (आधार के अनुसार)', emailLabel: 'ईमेल पता', passwordLabel: 'पासवर्ड', forgotPassword: 'पासवर्ड भूल गए?', passwordPlaceholder: 'सुरक्षित पासवर्ड बनाएँ', passwordLoginPlaceholder: 'पासवर्ड दर्ज करें', rememberMe: 'मुझे साइन इन रखें', signInBtn: 'SchemeReady में साइन इन करें', signUpBtn: 'नागरिक खाता बनाएँ', processing: 'सुरक्षित रूप से प्रक्रिया हो रही है…', noAccountYet: 'अभी SchemeReady खाता नहीं है?', registerNew: 'नया खाता रजिस्टर करें →', alreadyAccount: 'पहले से खाता है?', signInHere: 'यहाँ साइन इन करें →' }, assistant: { title: 'SchemeReady से पूछें', close: 'सहायक बंद करें', listening: 'सुन रहा है…', speak: 'बोलें', stopListening: 'सुनना बंद करें', send: 'संदेश भेजें', stopSpeaking: 'बोलना बंद करें', startSpeaking: 'जोर से पढ़ें', online: 'वॉइस तैयार', textFallback: 'इस ब्राउज़र में वॉइस उपलब्ध नहीं है। नीचे अपना प्रश्न लिखें।', schemeDetails: 'योजना विवरण', eligibility: 'पात्रता', benefits: 'लाभ', documents: 'दस्तावेज़', application: 'आवेदन कैसे करें', nextStep: 'अगला कदम' }
  },
  kn: {
    appTitle: 'ಸ್ಕೀಮ್‌ರೆಡಿ', appSubtitle: 'ಯೋಜನೆ ಹುಡುಕುವುದರಿಂದ ಅರ್ಜಿ ಸಿದ್ಧತೆಯವರೆಗೆ', tagline: 'ಉದ್ಯಮಿಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಹಾಗೂ ಚಾನಲ್ ಪಾಲುದಾರರಿಗೆ ಸಂಪರ್ಕಿಸುವುದು.', demoPersonaBtn: 'ಡೆಮೊ ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಮಾಡಿ (ರವಿ - ಬೆಂಗಳೂರು)', loginBtn: 'ಲಾಗಿನ್ / ನೋಂದಣಿ', profileTab: 'ಫಲಾನುಭವಿ ಪ್ರೊಫೈಲ್',
    tabs: { onboarding: '1. ಸ್ಮಾರ್ಟ್ ಆನ್‌ಬೋರ್ಡಿಂಗ್', profile: 'ಪ್ರೊಫೈಲ್ ಡೋಸಿಯರ್', schemes: '2. ಯೋಜನೆ ಹೊಂದಾಣಿಕೆ', readiness: '3. ಅರ್ಜಿ ಸಿದ್ಧತಾ ಸ್ಕೋರ್', businessPlan: '4. AI ಯೋಜನಾ ವರದಿ', checklist: '5. ದಾಖಲೆಗಳ ಪಟ್ಟಿ', partners: '6. ಪಾಲುದಾರರ ಮಾರ್ಗ', emi: '7. EMI ಸಿಮ್ಯುಲೇಟರ್', applicationPack: '8. ಅರ್ಜಿ ಪ್ಯಾಕ್', admin: 'ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್' },
    onboarding: { title: 'ಸ್ಮಾರ್ಟ್ ಫಲಾನುಭವಿ ಆನ್‌ಬೋರ್ಡಿಂಗ್', subtitle: 'ಕೆಲವು ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಅಥವಾ ಧ್ವನಿಯಿಂದ ಮಾತನಾಡಿ ಸೂಕ್ತ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.', voiceBtn: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ (ಮಾತನಾಡಿ)', listening: 'ಆಲಿಸುತ್ತಿದೆ… ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ', extractedBadge: 'ಗುರುತಿಸಿದ ಫಲಾನುಭವಿ ಪ್ರೊಫೈಲ್', q1: 'ನೀವು ಯಾವ ವ್ಯಾಪಾರ ಅಥವಾ ಕೆಲಸ ಆರಂಭಿಸಲು ಬಯಸುತ್ತೀರಿ?', q2: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಎಲ್ಲಿದೆ?', q3: 'ಅಂದಾಜು ಯೋಜನಾ ವೆಚ್ಚ ಎಷ್ಟು?', q4: 'ನಿಮ್ಮ ಕುಟುಂಬದ ವಾರ್ಷಿಕ ಆದಾಯ ಎಷ್ಟು?', q5: 'ನೀವು ವಿದ್ಯಾರ್ಥಿ, ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಉದ್ಯಮಿ ಅಥವಾ ಮೊದಲ ಬಾರಿಗೆ ಉದ್ಯಮಿಯೇ?', q6: 'ನಿಮ್ಮ ಬಳಿ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರವಿದೆಯೇ?', q7: 'ನಿಮ್ಮ ಬಳಿ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ ಅಥವಾ ITR ಇದೆಯೇ?', q8: 'ನಿಮಗೆ ಎಷ್ಟು ಸಾಲ ಬೇಕು?', q9: 'ಆನ್‌ಲೈನ್ ಅಥವಾ ಆಫ್‌ಲೈನ್ ಸಹಾಯ ಬಯಸುತ್ತೀರಾ?', q10: 'ಯಾವ ಭಾಷೆ ನಿಮಗೆ ಇಷ್ಟ?', nextBtn: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ', prevBtn: 'ಹಿಂದೆ', submitBtn: 'ಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ' },
    schemes: { title: 'ವಿವರಣಾತ್ಮಕ ಯೋಜನೆ ಶಿಫಾರಸುಗಳು', subtitle: 'ಯೋಜನೆ ಏಕೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ ಮತ್ತು ಏಕೆ ಇಲ್ಲ ಎಂಬ ಸ್ಪಷ್ಟ ಮಾಹಿತಿ.', matchScore: 'ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್', whyMatches: 'ಪೂರೈಸಿದ ಮಾನದಂಡಗಳು ಮತ್ತು ಹೊಂದಾಣಿಕೆಯ ಕಾರಣ:', whyNot: 'ಏಕೆ ಆಯ್ಕೆಯಾಗಿಲ್ಲ / ಸ್ಕೋರ್ ಕಡಿತ:', recommended: 'ಶಿಫಾರಸು ಮಾಡಿದ ಯೋಜನೆ', interestRate: 'ಬಡ್ಡಿ ದರ', maxLoan: 'ಗರಿಷ್ಠ ಸಾಲ ಮಿತಿ', tenure: 'ಗರಿಷ್ಠ ಅವಧಿ', source: 'ಅಧಿಕೃತ ಮೂಲ', verified: 'ಕೊನೆಯ ಪರಿಶೀಲನೆ', selectBtn: 'ಆಯ್ಕೆ ಮಾಡಿ ಮತ್ತು ಸಿದ್ಧತೆ ನೋಡಿ' },
    readiness: { title: 'ಅರ್ಜಿ ಸಿದ್ಧತಾ ಸ್ಕೋರ್', subtitle: 'ಬ್ಯಾಂಕ್ ಅಥವಾ SCA ಕಚೇರಿಗೆ ಹೋಗುವ ಮೊದಲು ಬಾಕಿ ಅಗತ್ಯಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.', scoreLabel: 'ಅರ್ಜಿ ಸಿದ್ಧತೆ', whyReq: 'ಏಕೆ ಅಗತ್ಯ:', howTo: 'ಹೇಗೆ ಪಡೆಯುವುದು:', accepted: 'ಸ್ವೀಕರಿಸುವ ಸ್ವರೂಪಗಳು:', uploadBtn: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', statusVerified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', statusComplete: 'ಪೂರ್ಣ', statusMissing: 'ಇಲ್ಲ', statusPending: 'ಪರಿಶೀಲನೆ ಬಾಕಿ' },
    businessPlan: { title: 'AI ವ್ಯವಹಾರ ಯೋಜನೆ ಮತ್ತು DPR', subtitle: 'ಸಲ್ಲಿಸಲು ಸಿದ್ಧವಾದ ಯೋಜನಾ ವರದಿ ರಚಿಸಿ.', generateBtn: 'ಯೋಜನಾ ವರದಿ ರಚಿಸಿ', dscr: 'ಸಾಲ ಸೇವಾ ವ್ಯಾಪ್ತಿ ಅನುಪಾತ (DSCR)', monthlySurplus: 'ಮಾಸಿಕ ಶುದ್ಧ ಉಳಿಕೆ', bankLoan: 'ಶಿಫಾರಸು ಮಾಡಿದ ಸಾಲ ಮೊತ್ತ' },
    partners: { title: 'ಸ್ಮಾರ್ಟ್ ಚಾನಲ್ ಪಾಲುದಾರ ಮಾರ್ಗ', subtitle: 'ಅರ್ಜಿಯನ್ನು ಸಲ್ಲಿಸಲು ಪರಿಶೀಲಿಸಿದ ಚಾನಲ್ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ.', recommendedBadge: 'ಶಿಫಾರಸು ಮಾಡಿದ ಸಮೀಪದ ಪಾಲುದಾರ', distance: 'ದೂರ', mode: 'ಅರ್ಜಿ ವಿಧಾನ', verifiedDate: 'ಕೊನೆಯ ಪರಿಶೀಲನೆ', contact: 'ಸಂಪರ್ಕ ಅಧಿಕಾರಿ' },
    emi: { title: 'EMI ಮತ್ತು ಹಣಕಾಸು ಕ್ಯಾಲ್ಕುಲೇಟರ್', subtitle: 'ಮಾಸಿಕ ಕಂತು, ಬಡ್ಡಿ ಮತ್ತು ಮೊರಟೋರಿಯಂ ಲೆಕ್ಕಹಾಕಿ.', monthlyEmi: 'ಮಾಸಿಕ EMI', totalInterest: 'ಒಟ್ಟು ಬಡ್ಡಿ', totalRepayment: 'ಒಟ್ಟು ಮರುಪಾವತಿ', moratoriumBuffer: 'ಮೊರಟೋರಿಯಂ ಅವಧಿ' },
    pack: { title: 'ಅರ್ಜಿ-ಸಿದ್ಧ ಪ್ಯಾಕ್', subtitle: 'ಪೂರ್ಣ ಡೋಸಿಯರ್ ಡೌನ್‌ಲೋಡ್, ಪ್ರಿಂಟ್ ಅಥವಾ ಹಸ್ತಾಂತರಿಸಿ.', downloadPdf: 'PDF ಡೌನ್‌ಲೋಡ್ / ಪ್ರಿಂಟ್', shareWhatsApp: 'WhatsApp ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ', handoffBtn: 'PM-SURAJ ಹಸ್ತಾಂತರಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ', disclaimer: 'ಇದು ಪ್ರಾಥಮಿಕ ಸಹಾಯ ದಾಖಲೆ. ಅಂತಿಮ ಅನುಮೋದನೆಯನ್ನು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಸಂಸ್ಥೆ ಅಥವಾ ಬ್ಯಾಂಕ್ ನಿರ್ಧರಿಸುತ್ತದೆ.' },
    navbar: { cleanBalanceSheet: '● ಕ್ಲೀನ್ ಬ್ಯಾಲೆನ್ಸ್ ಶೀಟ್ ಮತ್ತು 0% ಓವರ್‌ಡ್ಯೂ ಪರಿಶೀಲಿಸಲಾಗಿದೆ', sihEdition: 'SIH ಆವೃತ್ತಿ', raviPersona: 'ರವಿ ಪ್ರೊಫೈಲ್', demoPersonaTitle: 'ರವಿ ಡೆಮೊ ಪ್ರೊಫೈಲ್ ತುಂಬಿ', languageLabel: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ', primaryNavigation: 'ಮುಖ್ಯ ನ್ಯಾವಿಗೇಶನ್', signOut: 'ಸೈನ್ ಔಟ್', signIn: 'ಸೈನ್ ಇನ್' }, govHeader: { systemBanner: 'ಭಾರತ ಸರ್ಕಾರ ಮತ್ತು NSFDC ಚಾನೆಲ್ ಹಣಕಾಸು ವ್ಯವಸ್ಥೆ | PM-SURAJ ಅನುಗುಣ' }, common: { loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', close: 'ಮುಚ್ಚಿ', next: 'ಮುಂದೆ', back: 'ಹಿಂದೆ', search: 'ಹುಡುಕಿ', submit: 'ಸಲ್ಲಿಸಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', notAvailable: 'ಲಭ್ಯವಿಲ್ಲ', preliminary: 'ಪ್ರಾಥಮಿಕ ಮಾರ್ಗದರ್ಶನ' }, auth: { signInTab: 'ಖಾತೆಗೆ ಸೈನ್ ಇನ್', signUpTab: 'ನೋಂದಣಿ', loginHeading: 'ನಿಮ್ಮ ಫಲಾನುಭವಿ ಡೋಸಿಯರ್ ತೆರೆಯಿರಿ', signupHeading: 'ನಿಮ್ಮ ನಾಗರಿಕ ಖಾತೆ ರಚಿಸಿ', loginDesc: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಅರ್ಜಿ ಸಿದ್ಧತೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.', signupDesc: 'ಯೋಜನೆ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಅರ್ಜಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನೋಂದಣಿ ಮಾಡಿ.', fullNameLabel: 'ಪೂರ್ಣ ಹೆಸರು (ಆಧಾರ್‌ನಂತೆ)', emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ', passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್', forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?', passwordPlaceholder: 'ಸುರಕ್ಷಿತ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ', passwordLoginPlaceholder: 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ', rememberMe: 'ನನ್ನನ್ನು ಸೈನ್ ಇನ್ ಸ್ಥಿತಿಯಲ್ಲಿ ಇಡಿ', signInBtn: 'SchemeReady ಗೆ ಸೈನ್ ಇನ್', signUpBtn: 'ನಾಗರಿಕ ಖಾತೆ ರಚಿಸಿ', processing: 'ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತಿದೆ…', noAccountYet: 'SchemeReady ಖಾತೆ ಇಲ್ಲವೇ?', registerNew: 'ಹೊಸ ಖಾತೆ ನೋಂದಣಿ →', alreadyAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', signInHere: 'ಇಲ್ಲಿ ಸೈನ್ ಇನ್ ಮಾಡಿ →' }, assistant: { title: 'SchemeReady ಅನ್ನು ಕೇಳಿ', close: 'ಸಹಾಯಕ ಮುಚ್ಚಿ', listening: 'ಆಲಿಸುತ್ತಿದೆ…', speak: 'ಮಾತನಾಡಿ', stopListening: 'ಆಲಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ', send: 'ಸಂದೇಶ ಕಳುಹಿಸಿ', stopSpeaking: 'ಮಾತನಾಡುವುದನ್ನು ನಿಲ್ಲಿಸಿ', startSpeaking: 'ಧ್ವನಿಯಲ್ಲಿ ಓದಿ', online: 'ಧ್ವನಿ ಸಿದ್ಧವಾಗಿದೆ', textFallback: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ. ಕೆಳಗೆ ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ.', schemeDetails: 'ಯೋಜನೆ ವಿವರಗಳು', eligibility: 'ಅರ್ಹತೆ', benefits: 'ಪ್ರಯೋಜನಗಳು', documents: 'ದಾಖಲೆಗಳು', application: 'ಅರ್ಜಿ ಹೇಗೆ ಸಲ್ಲಿಸಬೇಕು', nextStep: 'ಮುಂದಿನ ಹಂತ' }
  }
};

const localeFallback = { ta: 'en', te: 'en', mr: 'hi', bn: 'hi' };
export function getTranslations(lang = 'en') { return translations[lang] || translations[localeFallback[lang]] || translations.en; }
export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', speech: 'en-IN' },
  { code: 'kn', label: 'ಕನ್ನಡ (Kannada)', speech: 'kn-IN' },
  { code: 'hi', label: 'हिन्दी (Hindi)', speech: 'hi-IN' },
  { code: 'ta', label: 'தமிழ் (Tamil)', speech: 'ta-IN' },
  { code: 'te', label: 'తెలుగు (Telugu)', speech: 'te-IN' },
  { code: 'mr', label: 'मराठी (Marathi)', speech: 'mr-IN' },
  { code: 'bn', label: 'বাংলা (Bengali)', speech: 'bn-IN' }
];
